version: '3.8'

services:
  apache:
    image: php:8.1-apache
    container_name: lamp_apache
    volumes:
      - ./studenti:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    # instalăm extensia mysqli și apoi pornim Apache
    command: >
      bash -c "docker-php-ext-install mysqli &&
               docker-php-ext-enable mysqli &&
               apache2-foreground"

  mysql:
    image: mysql:5.7
    container_name: lamp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studenti   # baza creată automat la prima pornire (tu folosești layerlab, e ok)
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
